# Generated by Django 4.0.5 on 2022-06-04 17:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastName', models.CharField(max_length=50, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_r', models.CharField(max_length=50, verbose_name='Название на русском')),
                ('name_o', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название на языке оригинала')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0, message='Минимальное количество составляет 0'), django.core.validators.MaxValueValidator(10, message='Максимальное количество составляет 10')])),
                ('price_for_day', models.DecimalField(decimal_places=2, max_digits=6)),
                ('year_of_made', models.IntegerField(error_messages={'unique': 'Год может состоять из 4 чисел'}, max_length=4)),
                ('date_of_register', models.DateField(auto_now_add=True)),
                ('count_of_pages', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество страниц должно составлять 1')])),
                ('authors', models.ManyToManyField(to='books.authors')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='FotosAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='authors')),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='books.authors')),
            ],
        ),
        migrations.CreateModel(
            name='FotoBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='books')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='books.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(to='books.genres'),
        ),
    ]
