# Generated by Django 4.0.5 on 2022-06-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_of_made',
            field=models.IntegerField(error_messages={'maxLength': 'Год может состоять из 4 чисел'}, max_length=4),
        ),
        migrations.AlterField(
            model_name='genres',
            name='genre',
            field=models.CharField(error_messages={'unique': 'Такой жанр уже добавлен'}, max_length=50, unique=True, verbose_name='Жанр'),
        ),
    ]
