# Generated by Django 4.0.5 on 2022-06-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30, verbose_name='Логин')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('sur_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=40, verbose_name='Email')),
                ('tel', models.CharField(max_length=40, verbose_name='Номер телефона')),
            ],
        ),
    ]
