# Generated by Django 4.0.5 on 2022-06-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
